# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170511_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
