# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:05
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='plop', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
