# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170511_1118'),
        ('post', '0004_auto_20170511_1105'),
    ]

    operations = [
    ]
