# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20170511_1135'),
        ('post', '0005_merge_20170511_1126'),
    ]

    operations = [
    ]
